In [1]:
import numpy as np
import pandas as pd
import os
from random import shuffle
from tqdm import tqdm

DATA_DIR = '../input/amazon/'
TRAIN_TIF_DIR = DATA_DIR + 'train-tif/'
TRAIN_CSV = DATA_DIR + 'train.csv'
TEST_TIF_DIR = DATA_DIR + 'test-tif/'

IMG_SIZE = 100
LR = 1e-3

MODEL_NAME = 'amazon=-{}-{}.model'.format(LR, '2conv-basic')

CLOUD_COVER_LABELS = [
    'clear', 
    'cloudy', 
    'haze', 
    'partly_cloudy']

# read our data and take a look at what we are dealing with
train_csv = pd.read_csv(TRAIN_CSV)
train_csv.head()

tags = pd.DataFrame()

for label in CLOUD_COVER_LABELS:
    tags[label] = train_csv.tags.apply(lambda x: np.where(label in x, 1, 0))
    
train_csv = pd.concat([train_csv, tags], axis=1)

In [17]:
pd.concat([train_csv[train_csv.clear == 1].sample(n=7251),
train_csv[train_csv.cloudy == 1].sample(n=7251),
train_csv[train_csv.haze == 1],
train_csv[train_csv.partly_cloudy == 1].sample(n=7251)], axis=0, ignore_index=True)

,image_name,tags,clear,cloudy,haze,partly_cloudy
0,train_15881,agriculture clear primary road water,1,0,0,0
1,train_6429,clear primary,1,0,0,0
2,train_15897,clear primary,1,0,0,0
3,train_4660,clear primary selective_logging,1,0,0,0
4,train_33419,agriculture clear primary road,1,0,0,0
5,train_31639,clear habitation road,1,0,0,0
6,train_26868,clear primary,1,0,0,0
7,train_26768,agriculture clear primary,1,0,0,0
8,train_27307,clear primary water,1,0,0,0
9,train_36095,clear primary water,1,0,0,0
10,train_8594,clear primary,1,0,0,0
11,train_30973,clear primary,1,0,0,0
12,train_26065,agriculture clear primary road,1,0,0,0
13,train_30980,agriculture clear primary,1,0,0,0
14,train_27035,agriculture clear cultivation primary,1,0,0,0
15,train_39073,clear primary,1,0,0,0
16,train_36774,clear primary,1,0,0,0
17,train_19213,agriculture clear primary,1,0,0,0
18,train_8701,clear primary water,1,0,0,0
19,train_39556,clear primary,1,0,0,0
20,train_28706,agriculture clear cultivation habitation prima...,1,0,0,0
21,train_17979,agriculture clear primary,1,0,0,0
22,train_33652,clear primary,1,0,0,0
23,train_14608,clear primary,1,0,0,0
24,train_35116,agriculture clear habitation primary road,1,0,0,0
25,train_37012,clear primary,1,0,0,0
26,train_27614,clear primary,1,0,0,0
27,train_14859,agriculture clear primary road,1,0,0,0
28,train_3902,artisinal_mine clear primary water,1,0,0,0
29,train_37973,clear primary,1,0,0,0
...,...,...,...,...,...,...
24418,train_9371,agriculture partly_cloudy primary water,0,1,0,1
24419,train_27056,agriculture partly_cloudy primary road,0,1,0,1
24420,train_34493,partly_cloudy primary,0,1,0,1
24421,train_27135,agriculture partly_cloudy primary,0,1,0,1
24422,train_32000,partly_cloudy primary,0,1,0,1
24423,train_16739,agriculture partly_cloudy primary,0,1,0,1
24424,train_14643,partly_cloudy primary water,0,1,0,1
24425,train_15306,partly_cloudy primary,0,1,0,1
24426,train_12555,partly_cloudy primary,0,1,0,1
24427,train_1922,partly_cloudy primary,0,1,0,1
24428,train_6220,partly_cloudy primary water,0,1,0,1
24429,train_15131,agriculture partly_cloudy primary water,0,1,0,1
24430,train_32558,agriculture partly_cloudy primary,0,1,0,1
24431,train_37915,partly_cloudy primary,0,1,0,1
24432,train_27835,partly_cloudy primary,0,1,0,1
24433,train_4863,partly_cloudy primary,0,1,0,1
24434,train_2834,agriculture cultivation partly_cloudy primary ...,0,1,0,1
24435,train_9648,partly_cloudy primary,0,1,0,1
24436,train_1879,cultivation partly_cloudy primary selective_lo...,0,1,0,1
24437,train_17583,partly_cloudy primary,0,1,0,1
24438,train_34437,partly_cloudy primary,0,1,0,1
24439,train_32757,agriculture partly_cloudy primary road,0,1,0,1
24440,train_40404,bare_ground partly_cloudy primary,0,1,0,1
24441,train_39267,agriculture partly_cloudy primary,0,1,0,1
24442,train_6509,partly_cloudy primary,0,1,0,1
24443,train_38362,partly_cloudy primary,0,1,0,1
24444,train_2704,partly_cloudy primary,0,1,0,1
24445,train_16344,partly_cloudy primary,0,1,0,1
24446,train_7990,partly_cloudy primary,0,1,0,1
24447,train_32227,partly_cloudy primary,0,1,0,1